### ISSUE TITLE
The confidence model mentioned in the article could not be found

### ISSUE THREAD

**Issue by Romarin87** [chenruduan/OAReactDiff#2]
Hello, I want to try the confidence model mentioned in the article to do some tests, but I did not find it, for example, `ddpm-epoch=2074-val-totloss=531.18.ckpt` in `generate_confidence_sample.py`.

**Comment by chenruduan** [comment]
Thanks for the interest! I uploaded the confidence model to https://zenodo.org/records/11118125. It is a `ConfModule` object, which inherent from `LightningModule`. So it can be used in a similar way as the diffusion model checkpoint.
