### ISSUE TITLE
No access

### ISSUE THREAD

**Issue by Anirudh-Dutta** [chenruduan/OAReactDiff#6]
When doing 
git clone git@github.com:chenruduan/OAReactDiff.git

It returns error:
Cloning into 'OAReactDiff'...
Warning: Permanently added 'github.com,140.82.116.4' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Edit - 
Fix is :
git clone https://github.com/chenruduan/OAReactDiff.git

**Comment by chenruduan** [comment]
quite interesting. it worked for me previously but does not work now. a quick walk around is to use https option.

**Comment by Anirudh-Dutta** [comment]
> quite interesting. it worked for me previously but does not work now. a quick walk around is to use https option.

Noted, 
Currently downloaded the repo and manually created env and initiated it.

Update-
This method does not work, as I run into a new error:

CondaError: Run 'conda init' before 'conda activate'

(Note - I'm using Kaggle to execute my code)
