### ISSUE TITLE
What is the ediff means in the transition1x dataset given in the repository?

### ISSUE THREAD

**Issue by littlepeachs** [chenruduan/OAReactDiff#7]
Hello, when I use the dataset given in the repository to train the confidence model, I find the target-key is set to "ediff", what is the key "ediff" mean and how it is calculated? Thanks!

**Comment by chenruduan** [comment]
ediff is the reaction barrier. We trained a separate model for barrier prediction, which is not included in to the paper as it would add extra complications in the storyline.
